ignoredThreads:
  - "containerd-shim-runc-v2"
  - "abrtd"
  - "abrt-watch-log"
  - "agetty"
  - "ata_sff"
  - "atd"
  - "auditd"
  - "bioset"
  - "bond0"
  - "bond1"
  - "cleanup"
  - "crond"
  - "crypto"
  - "dhclient"
  - "docker-proxy"
  - "dbus-daemon"
  - "deferwq"
  - "ext4-rsv-conver"
  - "fsnotify_mark"
  - "i40e"
  - "ib-comp-unb-wq"
  - "ib-comp-wq"
  - "ib_mad1"
  - "ib_mcast"
  - "ib_nl_sa_wq"
  - "ipv6_addrconf"
  - "irqbalance"
  - "ixgbe"
  - "jbd2"
  - "kauditd"
  - "kblockd"
  - "kdevtmpfs"
  - "khugepaged"
  - "khungtaskd"
  - "kintegrityd"
  - "kipmi0"
  - "kmpath_rdacd"
  - "kpsmoused"
  - "ksmd"
  - "ksoftirqd"
  - "kswapd0"
  - "kswapd1"
  - "kthreadd"
  - "kthrotld"
  - "kvm-irqfd-clean"
  - "kworker"
  - "local"
  - "lsmd"
  - "lvmetad"
  - "master"
  - "md"
  - "migration"
  - "mkey_cache"
  - "mlx4"
  - "mlx4_ib"
  - "mlx4_ib_mcg"
  - "mlx5_cmd_0000:5"
  - "mlx5e"
  - "mlx5e_arfs"
  - "mlx5_events"
  - "mlx5_fc"
  - "mlx5_fw_tracer"
  - "mlx5_health0000"
  - "mlx5_ib_sigerr_"
  - "mlx5_lag"
  - "mlx5_page_alloc"
  - "netns"
  - "nfit"
  - "ntpd"
  - "pickup"
  - "polkitd"
  - "poll_mpt3sas0_h"
  - "poll_mpt3sas0_s"
  - "qmgr"
  - "rcu_bh"
  - "rcu_sched"
  - "rdma_cm"
  - "rdma-ndd"
  - "rngd"
  - "rsyslogd"
  - "scsi_eh_0"
  - "scsi_eh_1"
  - "scsi_eh_10"
  - "scsi_eh_11"
  - "scsi_eh_12"
  - "scsi_eh_13"
  - "scsi_eh_14"
  - "scsi_eh_2"
  - "scsi_eh_3"
  - "scsi_eh_4"
  - "scsi_eh_5"
  - "scsi_eh_6"
  - "scsi_eh_7"
  - "scsi_eh_8"
  - "scsi_eh_9"
  - "scsi_tmf_0"
  - "scsi_tmf_1"
  - "scsi_tmf_10"
  - "scsi_tmf_11"
  - "scsi_tmf_12"
  - "scsi_tmf_13"
  - "scsi_tmf_14"
  - "scsi_tmf_2"
  - "scsi_tmf_3"
  - "scsi_tmf_4"
  - "scsi_tmf_5"
  - "scsi_tmf_6"
  - "scsi_tmf_7"
  - "scsi_tmf_8"
  - "scsi_tmf_9"
  - "smartd"
  - "sshd"
  - "systemd"
  - "systemd-journal"
  - "systemd-logind"
  - "systemd-udevd"
  - "to_fifo"
  - "trivial-rewrite"
  - "tuned"
  - "watchdog"
  - "writeback"
kernelThreadCheckScript: "/tmp/check_kernel_script_x0xweu.sh"